[package]
name = "effective_modes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.4"
plotters = "0.3.5"
ndarray = "0.16.1"
gnuplot = "0.0.43"